version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gha:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gomod:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "monthly"
    groups:
      npm:
        patterns: ["*"]

  - package-ecosystem: "terraform"
    directory: ".github/deploy"
    schedule:
      interval: "monthly"
    groups:
      terraform:
        patterns: ["*"]
