version: "3.8"

services:
    web:
        image: ghcr.io/taiidani/guess-my-word:latest
        depends_on: [ "app" ]
        ports: [ "127.0.0.1:8080:80" ]

    app:
        image: ghcr.io/taiidani/guess-my-word:latest
        depends_on: [ "redis" ]
        command: [ "/app" ]
        ports: [ "127.0.0.1:3000:3000" ]
        build: .
        environment:
            ADDR: "0.0.0.0"
            REDIS_ADDR: "redis:6379"

    redis:
        image: redis:6
        ports: [ "127.0.0.1:6379:6379" ]
