version: "3.8"

services:
    app:
        image: ghcr.io/taiidani/guess-my-word:latest
        build: .
        environment:
            ADDR: "0.0.0.0"
            REDIS_URL: "redis:6379"

    redis:
        image: redis:6
        ports: [ "127.0.0.1:6379:6379" ]
