- hosts: 10.0.1.2
  user: pi
  become: true
  gather_facts: false
  tasks:
    - name: Upload Binary
      copy:
        src: ../bin/guess-my-word
        dest: /usr/local/bin/guess-my-word
        owner: root
        group: root
        mode: 0755

    - name: Upload Service
      copy:
        src: guess-my-word.service
        dest: /etc/systemd/system/guess-my-word.service
        owner: root
        group: root
        mode: 0644

    - name: Enable Service
      systemd:
        name: guess-my-word
        state: restarted
        enabled: true

    - name: Upload Consul config
      copy:
        src: consul.hcl
        dest: /etc/consul.d/guess-my-word.hcl
        owner: consul
        group: consul
        mode: 0644

    - name: Register Consul config
      command: consul reload