name: deploy

on:
  - push

jobs:
  deliver:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_name: ${{ steps.outputs.outputs.image_name }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true

      - name: build
        env:
          CGO_ENABLED: 0
        run: go build

      - name: test
        run: ./guess_my_word --help

      - name: setup buildx
        uses: docker/setup-buildx-action@v2

      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: publish
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.ref_name == 'main' }}
          provenance: true
          sbom: true
          target: dist
          tags: "ghcr.io/taiidani/guess-my-word:${{ github.sha }}"

      - name: outputs
        id: outputs
        run: echo "image_name=ghcr.io/taiidani/guess-my-word:${{ github.sha }}" >> "$GITHUB_OUTPUT"

  deploy:
    needs: deliver
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://guessmyword.xyz
    concurrency: deployment
    if: github.ref_name == 'main'
    permissions:
      contents: read
      id-token: write # Needed for Vault JWT
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: vault
        id: vault
        uses: hashicorp/vault-action@v2
        with:
          url: https://rnd.vault.0846e66f-a975-4a88-9e46-6dc6267e9b73.aws.hashicorp.cloud:8200
          role: github-role
          method: jwt
          path: github
          namespace: admin
          jwtGithubAudience: https://github.com/taiidani
          secrets: |
            credentials/data/github TFC_TOKEN | TFC_TOKEN


      - name: setup-terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          terraform_version: 1.4.2
          cli_config_credentials_token: ${{ steps.vault.outputs.TFC_TOKEN }}

      - name: init
        working-directory: .github/deploy
        run: terraform init

      - name: validate
        working-directory: .github/deploy
        run: terraform validate -no-color

      - name: apply
        working-directory: .github/deploy
        run: terraform apply -auto-approve -input=false -var 'image_name=${{needs.deliver.outputs.image_name}}'
