name: deploy

on:
  - push

jobs:
  deliver:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_name: ${{ steps.outputs.outputs.image_name }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true

      - name: build
        env:
          CGO_ENABLED: 0
        run: go build

      - name: test
        run: ./guess_my_word --help

      - name: setup buildx
        uses: docker/setup-buildx-action@v2

      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: publish
        uses: docker/build-push-action@v4
        with:
          context: .
          # push: ${{ github.ref_name == 'main' }}
          push: true
          provenance: true
          sbom: true
          target: dist
          tags: "ghcr.io/taiidani/guess-my-word:${{ github.sha }}"

      - name: outputs
        id: outputs
        run: echo "image_name=ghcr.io/taiidani/guess-my-word:${{ github.sha }}" >> "$GITHUB_OUTPUT"

  deploy:
    needs: deliver
    runs-on: ubuntu-latest
    environment: production
    concurrency: deployment
    # if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup-terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          terraform_version: 1.4.2
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

      - name: init
        working-directory: .github/deploy
        run: terraform init

      - name: validate
        working-directory: .github/deploy
        run: terraform validate -no-color

      - name: apply
        working-directory: .github/deploy
        run: terraform apply -auto-approve -input=false -var 'image_name=${{needs.deliver.outputs.image_name}}'
