name: go

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - name: Get dependencies
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Lint
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@v0.3.0
          staticcheck -tests ./...
