name: go

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true

      - name: Get dependencies
        run: go mod download

      - name: Vet
        run: go vet ./...

      - uses: dominikh/staticcheck-action@v1
        with:
          version: "2022.1.1"
