name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Lint
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@v0.3.0
          staticcheck -tests ./...

      - name: Test
        run: go test -race -covermode=atomic -cover ./...
