name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4

      - name: Get dependencies
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Lint
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@v0.1.3
          staticcheck -tests ./...

      - name: Test
        run: go test -race -covermode=atomic -cover ./...
