name: main

on:
  push:
    branches:
      - "taiidani/DOSpacesUpload"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: "0"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true

      - run: go build -o ./guess-my-word

      - uses: actions/upload-artifact@v4
        with:
          name: "artifact"
          path: ./guess-my-word
          if-no-files-found: error
          retention-days: 1

  upload:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write # Needed for Vault JWT
    outputs:
      version: ${{ steps.outputs.outputs.version }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: "artifact"
          path: ./guess-my-word

      - name: vault
        id: vault
        uses: hashicorp/vault-action@v2
        with:
          url: https://rnd.vault.0846e66f-a975-4a88-9e46-6dc6267e9b73.aws.hashicorp.cloud:8200
          role: github-role
          method: jwt
          path: github
          namespace: admin
          jwtGithubAudience: https://github.com/taiidani
          secrets: |
            credentials/data/digitalocean/spaces spaces_access_id | AWS_ACCESS_KEY_ID ;
            credentials/data/digitalocean/spaces spaces_secret_key | AWS_SECRET_ACCESS_KEY

      - name: s3
        id: outputs
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.vault.outputs.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.vault.outputs.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp ./guess-my-word/guess-my-word s3://rnd-public/guess-my-word/v$(date +'%Y.%m.%d')-${GITHUB_SHA::6}_linux_amd64
          echo "version=https://rnd-public.sfo3.digitaloceanspaces.com/guess-my-word/v$(date +'%Y.%m.%d')-${GITHUB_SHA::6}_linux_amd64" >> "$GITHUB_OUTPUT"

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: upload
    with:
      artifact_url: "${{ needs.upload.outputs.version }}"
