name: test

on: [push]

jobs:
  playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: ["go"]
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4

      - name: Build
        run: mise run build

      - name: Run Dependencies
        run: docker compose up -d --wait

      - name: Run App
        run: |
          ./guess-my-word --help
          ./guess-my-word &

      - working-directory: web
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: web
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: web
        run: npx playwright test

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: playwright-report
          path: web/playwright-report/
          retention-days: 30
